name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "examples/**"
      - "Cargo.*"
      - ".github/**"
  # Able to call by other workflow
  workflow_call:
  # Able to call on GitHub
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  markdown_lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.yaml
          files: '*.md'
          ignore: target
          version: 0.28.1
